CREATE TABLE page (
    page_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_title varchar UNIQUE NOT NULL CHECK( page_title <> ''),
    page_link varchar UNIQUE NOT NULL CHECK( page_link <> '')
);

CREATE TABLE links (
    page_id bigint references page(page_id),
    link_id bigint references page(page_id),
    PRIMARY KEY (page_id, link_id),
    CHECK (page_id != link_id)
)